import cv2
import torch

model = torch.hub.load(
    'ultralytics/yolov5',
    'custom',
    path='best.pt',
    trust_repo=True
)

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if not ret:
        print("Camera error")
        break

    results = model(frame)
    annotated = results.render()[0]

    cv2.imshow("Helmet Detection", annotated)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()